/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) getUdqp_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {6, 6, 1};
static const casadi_int casadi_s2[10] = 
  {6, 1, 0, 6, 0, 1, 2, 3,
  4, 5};
static const casadi_int casadi_s3[45] = 
  {6, 6, 0, 6, 12, 18, 24, 30,
  36, 0, 1, 2, 3, 4, 5, 0,
  1, 2, 3, 4, 5, 0, 1, 2,
  3, 4, 5, 0, 1, 2, 3, 4,
  5, 0, 1, 2, 3, 4, 5, 0,
  1, 2, 3, 4, 5};

/* func3:(i0[6],i1[6],i2[6])->(o0[6x6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a000, a001, a002, a003, a004, a005, a006, a007, a008, a009, a010, a011;
  casadi_real a012, a013, a014, a015, a016, a017, a018, a019, a020, a021, a022, a023;
  casadi_real a024, a025, a026, a027, a028, a029, a030, a031, a032, a033, a034, a035;
  casadi_real a036, a037, a038, a039, a040, a041, a042, a043, a044, a045, a046, a047;
  casadi_real a048, a049, a050, a051, a052, a053, a054, a055, a056, a057, a058, a059;
  casadi_real a060, a061, a062, a063, a064, a065, a066, a067, a068, a069, a070, a071;
  casadi_real a072, a073, a074, a075, a076, a077, a078, a079, a080, a081, a082, a083;
  casadi_real a084, a085, a086, a087, a088, a089, a090, a091, a092, a093, a094, a095;
  casadi_real a096, a097, a098, a099, a100, a101, a102, a103;
  a000=2000.;
  a001=2.;
  a002=1.;
  a003=arg[2]? arg[2][0] : 0;
  a004=arg[2]? arg[2][2] : 0;
  a005=(a003-a004);
  a006=casadi_sq(a005);
  a007=arg[2]? arg[2][1] : 0;
  a008=arg[2]? arg[2][3] : 0;
  a009=(a007-a008);
  a010=casadi_sq(a009);
  a006=(a006+a010);
  a010=9.9999999999999998e-13;
  a006=(a006+a010);
  a006=sqrt(a006);
  a011=1.6000000000000000e-01;
  a012=(a006-a011);
  a013=1.0000000000000000e-03;
  a012=(a012/a013);
  a012=(-a012);
  a012=exp(a012);
  a014=(a002+a012);
  a015=log(a014);
  a015=(a001*a015);
  a016=(a005/a006);
  a017=arg[1]? arg[1][0] : 0;
  a017=(a003-a017);
  a018=1.0000000000000000e-02;
  a017=(a017/a018);
  a019=arg[1]? arg[1][2] : 0;
  a019=(a004-a019);
  a019=(a019/a018);
  a020=(a017-a019);
  a021=(a016*a020);
  a022=(a009/a006);
  a023=arg[1]? arg[1][1] : 0;
  a023=(a007-a023);
  a023=(a023/a018);
  a024=arg[1]? arg[1][3] : 0;
  a024=(a008-a024);
  a024=(a024/a018);
  a025=(a023-a024);
  a026=(a022*a025);
  a021=(a021+a026);
  a026=5.0000000000000000e-01;
  a021=(a021/a026);
  a027=0.;
  a028=(a021<a027);
  a029=(a002-a021);
  a029=(a028?a029:0);
  a030=(!a028);
  a031=(a021<a001);
  a021=(a021-a001);
  a032=casadi_sq(a021);
  a033=4.;
  a032=(a032/a033);
  a032=(a031?a032:0);
  a032=(a030?a032:0);
  a029=(a029+a032);
  a032=(a015*a029);
  a034=(1./a006);
  a035=(a016/a006);
  a036=(a005/a006);
  a037=(a035*a036);
  a037=(a034-a037);
  a038=(a032*a037);
  a039=(a020*a037);
  a040=100.;
  a041=(a040*a016);
  a039=(a039+a041);
  a041=(a022/a006);
  a042=(a041*a036);
  a043=(a025*a042);
  a039=(a039-a043);
  a039=(a001*a039);
  a043=(-a039);
  a043=(a028?a043:0);
  a044=2.5000000000000000e-01;
  a021=(a021+a021);
  a039=(a021*a039);
  a039=(a044*a039);
  a039=(a031?a039:0);
  a039=(a030?a039:0);
  a043=(a043+a039);
  a039=(a015*a043);
  a045=1000.;
  a036=(a045*a036);
  a036=(a012*a036);
  a036=(a036/a014);
  a036=(a001*a036);
  a046=(a029*a036);
  a039=(a039-a046);
  a046=(a016*a039);
  a038=(a038+a046);
  a046=-5.0000000000000000e-01;
  a047=(a025*a037);
  a048=(a040*a022);
  a049=(a020*a042);
  a048=(a048-a049);
  a047=(a047-a048);
  a048=(a046*a047);
  a048=(a015*a048);
  a049=(a016*a025);
  a050=(a022*a020);
  a049=(a049-a050);
  a050=(a046*a049);
  a036=(a050*a036);
  a048=(a048-a036);
  a048=(a029*a048);
  a036=(a050*a015);
  a043=(a036*a043);
  a048=(a048+a043);
  a043=2.5000000000000005e-03;
  a051=casadi_sq(a049);
  a051=(a043+a051);
  a051=sqrt(a051);
  a048=(a048/a051);
  a052=(a036*a029);
  a052=(a052/a051);
  a053=(a052/a051);
  a049=(a049+a049);
  a047=(a049*a047);
  a054=(a051+a051);
  a047=(a047/a054);
  a047=(a053*a047);
  a048=(a048-a047);
  a047=(a022*a048);
  a055=(a052*a042);
  a047=(a047-a055);
  a038=(a038-a047);
  a047=arg[2]? arg[2][4] : 0;
  a003=(a003-a047);
  a055=casadi_sq(a003);
  a056=arg[2]? arg[2][5] : 0;
  a007=(a007-a056);
  a057=casadi_sq(a007);
  a055=(a055+a057);
  a055=(a055+a010);
  a055=sqrt(a055);
  a057=(a055-a011);
  a057=(a057/a013);
  a057=(-a057);
  a057=exp(a057);
  a058=(a002+a057);
  a059=log(a058);
  a059=(a001*a059);
  a060=(a003/a055);
  a061=arg[1]? arg[1][4] : 0;
  a061=(a047-a061);
  a061=(a061/a018);
  a062=(a017-a061);
  a063=(a060*a062);
  a064=(a007/a055);
  a065=arg[1]? arg[1][5] : 0;
  a065=(a056-a065);
  a065=(a065/a018);
  a018=(a023-a065);
  a066=(a064*a018);
  a063=(a063+a066);
  a063=(a063/a026);
  a066=(a063<a027);
  a067=(a002-a063);
  a067=(a066?a067:0);
  a068=(!a066);
  a069=(a063<a001);
  a063=(a063-a001);
  a070=casadi_sq(a063);
  a070=(a070/a033);
  a070=(a069?a070:0);
  a070=(a068?a070:0);
  a067=(a067+a070);
  a070=(a059*a067);
  a071=(1./a055);
  a072=(a060/a055);
  a073=(a003/a055);
  a074=(a072*a073);
  a074=(a071-a074);
  a075=(a070*a074);
  a076=(a062*a074);
  a077=(a040*a060);
  a076=(a076+a077);
  a077=(a064/a055);
  a078=(a077*a073);
  a079=(a018*a078);
  a076=(a076-a079);
  a076=(a001*a076);
  a079=(-a076);
  a079=(a066?a079:0);
  a063=(a063+a063);
  a076=(a063*a076);
  a076=(a044*a076);
  a076=(a069?a076:0);
  a076=(a068?a076:0);
  a079=(a079+a076);
  a076=(a059*a079);
  a073=(a045*a073);
  a073=(a057*a073);
  a073=(a073/a058);
  a073=(a001*a073);
  a080=(a067*a073);
  a076=(a076-a080);
  a080=(a060*a076);
  a075=(a075+a080);
  a080=(a018*a074);
  a081=(a040*a064);
  a082=(a062*a078);
  a081=(a081-a082);
  a080=(a080-a081);
  a081=(a046*a080);
  a081=(a059*a081);
  a082=(a060*a018);
  a083=(a064*a062);
  a082=(a082-a083);
  a083=(a046*a082);
  a073=(a083*a073);
  a081=(a081-a073);
  a081=(a067*a081);
  a073=(a083*a059);
  a079=(a073*a079);
  a081=(a081+a079);
  a079=casadi_sq(a082);
  a079=(a043+a079);
  a079=sqrt(a079);
  a081=(a081/a079);
  a084=(a073*a067);
  a084=(a084/a079);
  a085=(a084/a079);
  a082=(a082+a082);
  a080=(a082*a080);
  a086=(a079+a079);
  a080=(a080/a086);
  a080=(a085*a080);
  a081=(a081-a080);
  a080=(a064*a081);
  a087=(a084*a078);
  a080=(a080-a087);
  a075=(a075-a080);
  a080=(a038+a075);
  a087=-9.8100000000000023e+00;
  a088=casadi_sq(a017);
  a089=casadi_sq(a023);
  a088=(a088+a089);
  a088=(a043+a088);
  a088=sqrt(a088);
  a089=(a087/a088);
  a090=-9.8100000000000021e-02;
  a091=(a090*a017);
  a091=(a091/a088);
  a091=(a091/a088);
  a017=(a017+a017);
  a017=(a040*a017);
  a092=(a088+a088);
  a017=(a017/a092);
  a093=(a091*a017);
  a089=(a089-a093);
  a080=(a080+a089);
  a080=(a000-a080);
  if (res[0]!=0) res[0][0]=a080;
  a037=(a052*a037);
  a048=(a016*a048);
  a037=(a037+a048);
  a039=(a022*a039);
  a042=(a032*a042);
  a039=(a039-a042);
  a037=(a037+a039);
  a074=(a084*a074);
  a081=(a060*a081);
  a074=(a074+a081);
  a076=(a064*a076);
  a078=(a070*a078);
  a076=(a076-a078);
  a074=(a074+a076);
  a076=(a037+a074);
  a078=(a090*a023);
  a078=(a078/a088);
  a078=(a078/a088);
  a017=(a078*a017);
  a076=(a076-a017);
  a076=(-a076);
  if (res[0]!=0) res[0][1]=a076;
  if (res[0]!=0) res[0][2]=a038;
  if (res[0]!=0) res[0][3]=a037;
  if (res[0]!=0) res[0][4]=a075;
  if (res[0]!=0) res[0][5]=a074;
  a074=(1./a006);
  a075=(a009/a006);
  a037=(a041*a075);
  a037=(a074-a037);
  a038=(a025*a037);
  a076=(a040*a022);
  a038=(a038+a076);
  a076=(a035*a075);
  a017=(a020*a076);
  a038=(a038-a017);
  a038=(a001*a038);
  a017=(-a038);
  a017=(a028?a017:0);
  a038=(a021*a038);
  a038=(a044*a038);
  a038=(a031?a038:0);
  a038=(a030?a038:0);
  a017=(a017+a038);
  a038=(a015*a017);
  a075=(a045*a075);
  a075=(a012*a075);
  a075=(a075/a014);
  a075=(a001*a075);
  a081=(a029*a075);
  a038=(a038-a081);
  a081=(a016*a038);
  a039=(a032*a076);
  a081=(a081-a039);
  a039=(a052*a037);
  a042=(a040*a016);
  a048=(a025*a076);
  a042=(a042-a048);
  a048=(a020*a037);
  a042=(a042-a048);
  a048=(a046*a042);
  a048=(a015*a048);
  a075=(a050*a075);
  a048=(a048-a075);
  a048=(a029*a048);
  a017=(a036*a017);
  a048=(a048+a017);
  a048=(a048/a051);
  a042=(a049*a042);
  a042=(a042/a054);
  a042=(a053*a042);
  a048=(a048-a042);
  a042=(a022*a048);
  a039=(a039+a042);
  a081=(a081-a039);
  a039=(1./a055);
  a042=(a007/a055);
  a017=(a077*a042);
  a017=(a039-a017);
  a075=(a018*a017);
  a080=(a040*a064);
  a075=(a075+a080);
  a080=(a072*a042);
  a089=(a062*a080);
  a075=(a075-a089);
  a075=(a001*a075);
  a089=(-a075);
  a089=(a066?a089:0);
  a075=(a063*a075);
  a075=(a044*a075);
  a075=(a069?a075:0);
  a075=(a068?a075:0);
  a089=(a089+a075);
  a075=(a059*a089);
  a042=(a045*a042);
  a042=(a057*a042);
  a042=(a042/a058);
  a042=(a001*a042);
  a093=(a067*a042);
  a075=(a075-a093);
  a093=(a060*a075);
  a094=(a070*a080);
  a093=(a093-a094);
  a094=(a084*a017);
  a095=(a040*a060);
  a096=(a018*a080);
  a095=(a095-a096);
  a096=(a062*a017);
  a095=(a095-a096);
  a096=(a046*a095);
  a096=(a059*a096);
  a042=(a083*a042);
  a096=(a096-a042);
  a096=(a067*a096);
  a089=(a073*a089);
  a096=(a096+a089);
  a096=(a096/a079);
  a095=(a082*a095);
  a095=(a095/a086);
  a095=(a085*a095);
  a096=(a096-a095);
  a095=(a064*a096);
  a094=(a094+a095);
  a093=(a093-a094);
  a094=(a081+a093);
  a023=(a023+a023);
  a023=(a040*a023);
  a023=(a023/a092);
  a091=(a091*a023);
  a094=(a094-a091);
  a094=(-a094);
  if (res[0]!=0) res[0][6]=a094;
  a048=(a016*a048);
  a076=(a052*a076);
  a048=(a048-a076);
  a037=(a032*a037);
  a038=(a022*a038);
  a037=(a037+a038);
  a048=(a048+a037);
  a096=(a060*a096);
  a080=(a084*a080);
  a096=(a096-a080);
  a017=(a070*a017);
  a075=(a064*a075);
  a017=(a017+a075);
  a096=(a096+a017);
  a017=(a048+a096);
  a088=(a087/a088);
  a078=(a078*a023);
  a088=(a088-a078);
  a017=(a017+a088);
  a017=(a000-a017);
  if (res[0]!=0) res[0][7]=a017;
  if (res[0]!=0) res[0][8]=a081;
  if (res[0]!=0) res[0][9]=a048;
  if (res[0]!=0) res[0][10]=a093;
  if (res[0]!=0) res[0][11]=a096;
  a005=(a005/a006);
  a096=(a035*a005);
  a096=(a096-a034);
  a034=(a032*a096);
  a093=(a045*a005);
  a093=(a012*a093);
  a093=(a093/a014);
  a093=(a001*a093);
  a048=(a029*a093);
  a081=(a020*a096);
  a017=-100.;
  a088=(a017*a016);
  a081=(a081+a088);
  a005=(a041*a005);
  a088=(a025*a005);
  a081=(a081+a088);
  a081=(a001*a081);
  a088=(-a081);
  a088=(a028?a088:0);
  a081=(a021*a081);
  a081=(a044*a081);
  a081=(a031?a081:0);
  a081=(a030?a081:0);
  a088=(a088+a081);
  a081=(a015*a088);
  a048=(a048+a081);
  a081=(a016*a048);
  a034=(a034+a081);
  a081=(a052*a005);
  a078=(a025*a096);
  a023=(a020*a005);
  a075=(a017*a022);
  a023=(a023+a075);
  a078=(a078-a023);
  a023=(a046*a078);
  a023=(a015*a023);
  a093=(a050*a093);
  a023=(a023+a093);
  a023=(a029*a023);
  a088=(a036*a088);
  a023=(a023+a088);
  a023=(a023/a051);
  a078=(a049*a078);
  a078=(a078/a054);
  a078=(a053*a078);
  a023=(a023-a078);
  a078=(a022*a023);
  a081=(a081+a078);
  a034=(a034-a081);
  a081=(-a034);
  if (res[0]!=0) res[0][12]=a081;
  a096=(a052*a096);
  a023=(a016*a023);
  a096=(a096+a023);
  a005=(a032*a005);
  a048=(a022*a048);
  a005=(a005+a048);
  a096=(a096+a005);
  a005=(-a096);
  if (res[0]!=0) res[0][13]=a005;
  a004=(a004-a047);
  a047=casadi_sq(a004);
  a008=(a008-a056);
  a056=casadi_sq(a008);
  a047=(a047+a056);
  a047=(a047+a010);
  a047=sqrt(a047);
  a011=(a047-a011);
  a011=(a011/a013);
  a011=(-a011);
  a011=exp(a011);
  a013=(a002+a011);
  a010=log(a013);
  a010=(a001*a010);
  a056=(a004/a047);
  a005=(a019-a061);
  a048=(a056*a005);
  a023=(a008/a047);
  a081=(a024-a065);
  a078=(a023*a081);
  a048=(a048+a078);
  a048=(a048/a026);
  a027=(a048<a027);
  a002=(a002-a048);
  a002=(a027?a002:0);
  a026=(!a027);
  a078=(a048<a001);
  a048=(a048-a001);
  a088=casadi_sq(a048);
  a088=(a088/a033);
  a088=(a078?a088:0);
  a088=(a026?a088:0);
  a002=(a002+a088);
  a088=(a010*a002);
  a033=(1./a047);
  a093=(a056/a047);
  a075=(a004/a047);
  a080=(a093*a075);
  a080=(a033-a080);
  a037=(a088*a080);
  a038=(a005*a080);
  a076=(a040*a056);
  a038=(a038+a076);
  a076=(a023/a047);
  a094=(a076*a075);
  a091=(a081*a094);
  a038=(a038-a091);
  a038=(a001*a038);
  a091=(-a038);
  a091=(a027?a091:0);
  a048=(a048+a048);
  a038=(a048*a038);
  a038=(a044*a038);
  a038=(a078?a038:0);
  a038=(a026?a038:0);
  a091=(a091+a038);
  a038=(a010*a091);
  a075=(a045*a075);
  a075=(a011*a075);
  a075=(a075/a013);
  a075=(a001*a075);
  a092=(a002*a075);
  a038=(a038-a092);
  a092=(a056*a038);
  a037=(a037+a092);
  a092=(a081*a080);
  a095=(a040*a023);
  a089=(a005*a094);
  a095=(a095-a089);
  a092=(a092-a095);
  a095=(a046*a092);
  a095=(a010*a095);
  a089=(a056*a081);
  a042=(a023*a005);
  a089=(a089-a042);
  a042=(a046*a089);
  a075=(a042*a075);
  a095=(a095-a075);
  a095=(a002*a095);
  a075=(a042*a010);
  a091=(a075*a091);
  a095=(a095+a091);
  a091=casadi_sq(a089);
  a091=(a043+a091);
  a091=sqrt(a091);
  a095=(a095/a091);
  a097=(a075*a002);
  a097=(a097/a091);
  a098=(a097/a091);
  a089=(a089+a089);
  a092=(a089*a092);
  a099=(a091+a091);
  a092=(a092/a099);
  a092=(a098*a092);
  a095=(a095-a092);
  a092=(a023*a095);
  a100=(a097*a094);
  a092=(a092-a100);
  a037=(a037-a092);
  a034=(a037-a034);
  a092=casadi_sq(a019);
  a100=casadi_sq(a024);
  a092=(a092+a100);
  a092=(a043+a092);
  a092=sqrt(a092);
  a100=(a087/a092);
  a101=(a090*a019);
  a101=(a101/a092);
  a101=(a101/a092);
  a019=(a019+a019);
  a019=(a040*a019);
  a102=(a092+a092);
  a019=(a019/a102);
  a103=(a101*a019);
  a100=(a100-a103);
  a034=(a034+a100);
  a034=(a000-a034);
  if (res[0]!=0) res[0][14]=a034;
  a080=(a097*a080);
  a095=(a056*a095);
  a080=(a080+a095);
  a038=(a023*a038);
  a094=(a088*a094);
  a038=(a038-a094);
  a080=(a080+a038);
  a096=(a080-a096);
  a038=(a090*a024);
  a038=(a038/a092);
  a038=(a038/a092);
  a019=(a038*a019);
  a096=(a096-a019);
  a096=(-a096);
  if (res[0]!=0) res[0][15]=a096;
  if (res[0]!=0) res[0][16]=a037;
  if (res[0]!=0) res[0][17]=a080;
  a009=(a009/a006);
  a035=(a035*a009);
  a006=(a032*a035);
  a080=(a045*a009);
  a012=(a012*a080);
  a012=(a012/a014);
  a012=(a001*a012);
  a014=(a029*a012);
  a080=(a020*a035);
  a041=(a041*a009);
  a041=(a041-a074);
  a074=(a025*a041);
  a009=(a017*a022);
  a074=(a074+a009);
  a080=(a080+a074);
  a080=(a001*a080);
  a074=(-a080);
  a028=(a028?a074:0);
  a021=(a021*a080);
  a021=(a044*a021);
  a031=(a031?a021:0);
  a030=(a030?a031:0);
  a028=(a028+a030);
  a030=(a015*a028);
  a014=(a014+a030);
  a030=(a016*a014);
  a006=(a006+a030);
  a030=(a052*a041);
  a025=(a025*a035);
  a031=(a017*a016);
  a025=(a025+a031);
  a020=(a020*a041);
  a025=(a025-a020);
  a020=(a046*a025);
  a015=(a015*a020);
  a050=(a050*a012);
  a015=(a015+a050);
  a029=(a029*a015);
  a036=(a036*a028);
  a029=(a029+a036);
  a029=(a029/a051);
  a049=(a049*a025);
  a049=(a049/a054);
  a053=(a053*a049);
  a029=(a029-a053);
  a053=(a022*a029);
  a030=(a030+a053);
  a006=(a006-a030);
  a030=(-a006);
  if (res[0]!=0) res[0][18]=a030;
  a052=(a052*a035);
  a016=(a016*a029);
  a052=(a052+a016);
  a032=(a032*a041);
  a022=(a022*a014);
  a032=(a032+a022);
  a052=(a052+a032);
  a032=(-a052);
  if (res[0]!=0) res[0][19]=a032;
  a032=(1./a047);
  a022=(a008/a047);
  a014=(a076*a022);
  a014=(a032-a014);
  a041=(a081*a014);
  a016=(a040*a023);
  a041=(a041+a016);
  a016=(a093*a022);
  a029=(a005*a016);
  a041=(a041-a029);
  a041=(a001*a041);
  a029=(-a041);
  a029=(a027?a029:0);
  a041=(a048*a041);
  a041=(a044*a041);
  a041=(a078?a041:0);
  a041=(a026?a041:0);
  a029=(a029+a041);
  a041=(a010*a029);
  a022=(a045*a022);
  a022=(a011*a022);
  a022=(a022/a013);
  a022=(a001*a022);
  a035=(a002*a022);
  a041=(a041-a035);
  a035=(a056*a041);
  a030=(a088*a016);
  a035=(a035-a030);
  a030=(a097*a014);
  a053=(a040*a056);
  a049=(a081*a016);
  a053=(a053-a049);
  a049=(a005*a014);
  a053=(a053-a049);
  a049=(a046*a053);
  a049=(a010*a049);
  a022=(a042*a022);
  a049=(a049-a022);
  a049=(a002*a049);
  a029=(a075*a029);
  a049=(a049+a029);
  a049=(a049/a091);
  a053=(a089*a053);
  a053=(a053/a099);
  a053=(a098*a053);
  a049=(a049-a053);
  a053=(a023*a049);
  a030=(a030+a053);
  a035=(a035-a030);
  a006=(a035-a006);
  a024=(a024+a024);
  a024=(a040*a024);
  a024=(a024/a102);
  a101=(a101*a024);
  a006=(a006-a101);
  a006=(-a006);
  if (res[0]!=0) res[0][20]=a006;
  a049=(a056*a049);
  a016=(a097*a016);
  a049=(a049-a016);
  a014=(a088*a014);
  a041=(a023*a041);
  a014=(a014+a041);
  a049=(a049+a014);
  a052=(a049-a052);
  a092=(a087/a092);
  a038=(a038*a024);
  a092=(a092-a038);
  a052=(a052+a092);
  a052=(a000-a052);
  if (res[0]!=0) res[0][21]=a052;
  if (res[0]!=0) res[0][22]=a035;
  if (res[0]!=0) res[0][23]=a049;
  a003=(a003/a055);
  a049=(a072*a003);
  a049=(a049-a071);
  a071=(a070*a049);
  a035=(a045*a003);
  a035=(a057*a035);
  a035=(a035/a058);
  a035=(a001*a035);
  a052=(a067*a035);
  a092=(a062*a049);
  a038=(a017*a060);
  a092=(a092+a038);
  a003=(a077*a003);
  a038=(a018*a003);
  a092=(a092+a038);
  a092=(a001*a092);
  a038=(-a092);
  a038=(a066?a038:0);
  a092=(a063*a092);
  a092=(a044*a092);
  a092=(a069?a092:0);
  a092=(a068?a092:0);
  a038=(a038+a092);
  a092=(a059*a038);
  a052=(a052+a092);
  a092=(a060*a052);
  a071=(a071+a092);
  a092=(a084*a003);
  a024=(a018*a049);
  a014=(a062*a003);
  a041=(a017*a064);
  a014=(a014+a041);
  a024=(a024-a014);
  a014=(a046*a024);
  a014=(a059*a014);
  a035=(a083*a035);
  a014=(a014+a035);
  a014=(a067*a014);
  a038=(a073*a038);
  a014=(a014+a038);
  a014=(a014/a079);
  a024=(a082*a024);
  a024=(a024/a086);
  a024=(a085*a024);
  a014=(a014-a024);
  a024=(a064*a014);
  a092=(a092+a024);
  a071=(a071-a092);
  a092=(-a071);
  if (res[0]!=0) res[0][24]=a092;
  a049=(a084*a049);
  a014=(a060*a014);
  a049=(a049+a014);
  a003=(a070*a003);
  a052=(a064*a052);
  a003=(a003+a052);
  a049=(a049+a003);
  a003=(-a049);
  if (res[0]!=0) res[0][25]=a003;
  a004=(a004/a047);
  a003=(a093*a004);
  a003=(a003-a033);
  a033=(a088*a003);
  a052=(a045*a004);
  a052=(a011*a052);
  a052=(a052/a013);
  a052=(a001*a052);
  a014=(a002*a052);
  a092=(a005*a003);
  a024=(a017*a056);
  a092=(a092+a024);
  a004=(a076*a004);
  a024=(a081*a004);
  a092=(a092+a024);
  a092=(a001*a092);
  a024=(-a092);
  a024=(a027?a024:0);
  a092=(a048*a092);
  a092=(a044*a092);
  a092=(a078?a092:0);
  a092=(a026?a092:0);
  a024=(a024+a092);
  a092=(a010*a024);
  a014=(a014+a092);
  a092=(a056*a014);
  a033=(a033+a092);
  a092=(a097*a004);
  a038=(a081*a003);
  a035=(a005*a004);
  a041=(a017*a023);
  a035=(a035+a041);
  a038=(a038-a035);
  a035=(a046*a038);
  a035=(a010*a035);
  a052=(a042*a052);
  a035=(a035+a052);
  a035=(a002*a035);
  a024=(a075*a024);
  a035=(a035+a024);
  a035=(a035/a091);
  a038=(a089*a038);
  a038=(a038/a099);
  a038=(a098*a038);
  a035=(a035-a038);
  a038=(a023*a035);
  a092=(a092+a038);
  a033=(a033-a092);
  a092=(-a033);
  if (res[0]!=0) res[0][26]=a092;
  a003=(a097*a003);
  a035=(a056*a035);
  a003=(a003+a035);
  a004=(a088*a004);
  a014=(a023*a014);
  a004=(a004+a014);
  a003=(a003+a004);
  a004=(-a003);
  if (res[0]!=0) res[0][27]=a004;
  a004=casadi_sq(a061);
  a014=casadi_sq(a065);
  a004=(a004+a014);
  a043=(a043+a004);
  a043=sqrt(a043);
  a004=(a087/a043);
  a014=(a090*a061);
  a014=(a014/a043);
  a014=(a014/a043);
  a061=(a061+a061);
  a061=(a040*a061);
  a035=(a043+a043);
  a061=(a061/a035);
  a092=(a014*a061);
  a004=(a004-a092);
  a033=(a033+a071);
  a004=(a004-a033);
  a004=(a000-a004);
  if (res[0]!=0) res[0][28]=a004;
  a090=(a090*a065);
  a090=(a090/a043);
  a090=(a090/a043);
  a061=(a090*a061);
  a003=(a003+a049);
  a061=(a061+a003);
  if (res[0]!=0) res[0][29]=a061;
  a007=(a007/a055);
  a072=(a072*a007);
  a055=(a070*a072);
  a061=(a045*a007);
  a057=(a057*a061);
  a057=(a057/a058);
  a057=(a001*a057);
  a058=(a067*a057);
  a061=(a062*a072);
  a077=(a077*a007);
  a077=(a077-a039);
  a039=(a018*a077);
  a007=(a017*a064);
  a039=(a039+a007);
  a061=(a061+a039);
  a061=(a001*a061);
  a039=(-a061);
  a066=(a066?a039:0);
  a063=(a063*a061);
  a063=(a044*a063);
  a069=(a069?a063:0);
  a068=(a068?a069:0);
  a066=(a066+a068);
  a068=(a059*a066);
  a058=(a058+a068);
  a068=(a060*a058);
  a055=(a055+a068);
  a068=(a084*a077);
  a018=(a018*a072);
  a069=(a017*a060);
  a018=(a018+a069);
  a062=(a062*a077);
  a018=(a018-a062);
  a062=(a046*a018);
  a059=(a059*a062);
  a083=(a083*a057);
  a059=(a059+a083);
  a067=(a067*a059);
  a073=(a073*a066);
  a067=(a067+a073);
  a067=(a067/a079);
  a082=(a082*a018);
  a082=(a082/a086);
  a085=(a085*a082);
  a067=(a067-a085);
  a085=(a064*a067);
  a068=(a068+a085);
  a055=(a055-a068);
  a068=(-a055);
  if (res[0]!=0) res[0][30]=a068;
  a084=(a084*a072);
  a060=(a060*a067);
  a084=(a084+a060);
  a070=(a070*a077);
  a064=(a064*a058);
  a070=(a070+a064);
  a084=(a084+a070);
  a070=(-a084);
  if (res[0]!=0) res[0][31]=a070;
  a008=(a008/a047);
  a093=(a093*a008);
  a047=(a088*a093);
  a045=(a045*a008);
  a011=(a011*a045);
  a011=(a011/a013);
  a011=(a001*a011);
  a013=(a002*a011);
  a045=(a005*a093);
  a076=(a076*a008);
  a076=(a076-a032);
  a032=(a081*a076);
  a008=(a017*a023);
  a032=(a032+a008);
  a045=(a045+a032);
  a001=(a001*a045);
  a045=(-a001);
  a027=(a027?a045:0);
  a048=(a048*a001);
  a044=(a044*a048);
  a078=(a078?a044:0);
  a026=(a026?a078:0);
  a027=(a027+a026);
  a026=(a010*a027);
  a013=(a013+a026);
  a026=(a056*a013);
  a047=(a047+a026);
  a026=(a097*a076);
  a081=(a081*a093);
  a017=(a017*a056);
  a081=(a081+a017);
  a005=(a005*a076);
  a081=(a081-a005);
  a046=(a046*a081);
  a010=(a010*a046);
  a042=(a042*a011);
  a010=(a010+a042);
  a002=(a002*a010);
  a075=(a075*a027);
  a002=(a002+a075);
  a002=(a002/a091);
  a089=(a089*a081);
  a089=(a089/a099);
  a098=(a098*a089);
  a002=(a002-a098);
  a098=(a023*a002);
  a026=(a026+a098);
  a047=(a047-a026);
  a026=(-a047);
  if (res[0]!=0) res[0][32]=a026;
  a097=(a097*a093);
  a056=(a056*a002);
  a097=(a097+a056);
  a088=(a088*a076);
  a023=(a023*a013);
  a088=(a088+a023);
  a097=(a097+a088);
  a088=(-a097);
  if (res[0]!=0) res[0][33]=a088;
  a065=(a065+a065);
  a040=(a040*a065);
  a040=(a040/a035);
  a014=(a014*a040);
  a047=(a047+a055);
  a014=(a014+a047);
  if (res[0]!=0) res[0][34]=a014;
  a087=(a087/a043);
  a090=(a090*a040);
  a087=(a087-a090);
  a097=(a097+a084);
  a087=(a087-a097);
  a000=(a000-a087);
  if (res[0]!=0) res[0][35]=a000;
  return 0;
}

CASADI_SYMBOL_EXPORT int func3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int func3_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int func3_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void func3_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int func3_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void func3_release(int mem) {
}

CASADI_SYMBOL_EXPORT void func3_incref(void) {
}

CASADI_SYMBOL_EXPORT void func3_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int func3_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int func3_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real func3_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* func3_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* func3_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* func3_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* func3_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int func3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int func3_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_func3(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  int mem;
  casadi_real w[158];
  casadi_int *iw = 0;
  const casadi_real* arg[3] = {0};
  casadi_real* res[1] = {0};
  if (argc>3) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"func3\" failed. Too many input arguments (%d, max 3)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"func3\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s2, w+54);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+6, casadi_s2, w+54);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+12, casadi_s2, w+54);
  --resc;
  res[0] = w+18;
  func3_incref();
  mem = func3_checkout();
  i = func3(arg, res, iw, w+54, mem);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"func3\" failed.");
  func3_release(mem);
  func3_decref();
  if (res[0]) resv[0] = casadi_to_mex(casadi_s3, res[0]);
}
#endif

casadi_int main_func3(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int *iw = 0;
  casadi_real w[158];
  const casadi_real* arg[3];
  casadi_real* res[1];
  arg[0] = w+0;
  arg[1] = w+6;
  arg[2] = w+12;
  res[0] = w+18;
  a = w;
  for (j=0; j<18; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = func3(arg, res, iw, w+54, 0);
  if (flag) return flag;
  r = w+18;
  for (j=0; j<36; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[6];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_func3(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "func3")==0) {
    mex_func3(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'func3'");
}
#endif
CASADI_SYMBOL_EXPORT int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "func3")==0) {
    return main_func3(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'func3'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
