/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) getU_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[10] = 
  {6, 1, 0, 6, 0, 1, 2, 3,
  4, 5};

/* func0:(i0[6],i1[6],i2[6])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41;
  a00=2.0000000000000001e-01;
  a01=arg[2]? arg[2][0] : 0;
  a02=arg[1]? arg[1][0] : 0;
  a03=(a01-a02);
  a04=1.0000000000000000e-02;
  a03=(a03/a04);
  a05=arg[0]? arg[0][0] : 0;
  a02=(a02-a05);
  a02=(a02/a04);
  a02=(a03-a02);
  a02=(a02/a04);
  a02=(a00*a02);
  a05=arg[2]? arg[2][2] : 0;
  a06=(a01-a05);
  a07=casadi_sq(a06);
  a08=arg[2]? arg[2][1] : 0;
  a09=arg[2]? arg[2][3] : 0;
  a10=(a08-a09);
  a11=casadi_sq(a10);
  a07=(a07+a11);
  a11=9.9999999999999998e-13;
  a07=(a07+a11);
  a07=sqrt(a07);
  a06=(a06/a07);
  a12=2.;
  a13=1.;
  a14=1.6000000000000000e-01;
  a15=(a07-a14);
  a16=1.0000000000000000e-03;
  a15=(a15/a16);
  a15=(-a15);
  a15=exp(a15);
  a15=(a13+a15);
  a15=log(a15);
  a15=(a12*a15);
  a17=arg[1]? arg[1][2] : 0;
  a18=(a05-a17);
  a18=(a18/a04);
  a19=(a03-a18);
  a20=(a06*a19);
  a10=(a10/a07);
  a07=arg[1]? arg[1][1] : 0;
  a21=(a08-a07);
  a21=(a21/a04);
  a22=arg[1]? arg[1][3] : 0;
  a23=(a09-a22);
  a23=(a23/a04);
  a24=(a21-a23);
  a25=(a10*a24);
  a20=(a20+a25);
  a25=5.0000000000000000e-01;
  a20=(a20/a25);
  a26=0.;
  a27=(a20<a26);
  a28=(a13-a20);
  a28=(a27?a28:0);
  a27=(!a27);
  a29=(a20<a12);
  a20=(a20-a12);
  a20=casadi_sq(a20);
  a30=4.;
  a20=(a20/a30);
  a29=(a29?a20:0);
  a27=(a27?a29:0);
  a28=(a28+a27);
  a27=(a15*a28);
  a29=(a06*a27);
  a20=-5.0000000000000000e-01;
  a24=(a06*a24);
  a19=(a10*a19);
  a24=(a24-a19);
  a19=(a20*a24);
  a19=(a19*a15);
  a19=(a19*a28);
  a28=2.5000000000000005e-03;
  a24=casadi_sq(a24);
  a24=(a28+a24);
  a24=sqrt(a24);
  a19=(a19/a24);
  a24=(a10*a19);
  a29=(a29-a24);
  a24=arg[2]? arg[2][4] : 0;
  a01=(a01-a24);
  a15=casadi_sq(a01);
  a31=arg[2]? arg[2][5] : 0;
  a08=(a08-a31);
  a32=casadi_sq(a08);
  a15=(a15+a32);
  a15=(a15+a11);
  a15=sqrt(a15);
  a01=(a01/a15);
  a32=(a15-a14);
  a32=(a32/a16);
  a32=(-a32);
  a32=exp(a32);
  a32=(a13+a32);
  a32=log(a32);
  a32=(a12*a32);
  a33=arg[1]? arg[1][4] : 0;
  a34=(a24-a33);
  a34=(a34/a04);
  a35=(a03-a34);
  a36=(a01*a35);
  a08=(a08/a15);
  a15=arg[1]? arg[1][5] : 0;
  a37=(a31-a15);
  a37=(a37/a04);
  a38=(a21-a37);
  a39=(a08*a38);
  a36=(a36+a39);
  a36=(a36/a25);
  a39=(a36<a26);
  a40=(a13-a36);
  a40=(a39?a40:0);
  a39=(!a39);
  a41=(a36<a12);
  a36=(a36-a12);
  a36=casadi_sq(a36);
  a36=(a36/a30);
  a41=(a41?a36:0);
  a39=(a39?a41:0);
  a40=(a40+a39);
  a39=(a32*a40);
  a41=(a01*a39);
  a38=(a01*a38);
  a35=(a08*a35);
  a38=(a38-a35);
  a35=(a20*a38);
  a35=(a35*a32);
  a35=(a35*a40);
  a38=casadi_sq(a38);
  a38=(a28+a38);
  a38=sqrt(a38);
  a35=(a35/a38);
  a38=(a08*a35);
  a41=(a41-a38);
  a38=(a29+a41);
  a40=-9.8100000000000021e-02;
  a32=(a40*a03);
  a03=casadi_sq(a03);
  a36=casadi_sq(a21);
  a03=(a03+a36);
  a03=(a28+a03);
  a03=sqrt(a03);
  a32=(a32/a03);
  a38=(a38+a32);
  a02=(a02-a38);
  if (res[0]!=0) res[0][0]=a02;
  a02=arg[0]? arg[0][1] : 0;
  a07=(a07-a02);
  a07=(a07/a04);
  a07=(a21-a07);
  a07=(a07/a04);
  a07=(a00*a07);
  a06=(a06*a19);
  a10=(a10*a27);
  a06=(a06+a10);
  a01=(a01*a35);
  a08=(a08*a39);
  a01=(a01+a08);
  a08=(a06+a01);
  a21=(a40*a21);
  a21=(a21/a03);
  a08=(a08+a21);
  a07=(a07-a08);
  if (res[0]!=0) res[0][1]=a07;
  a07=arg[0]? arg[0][2] : 0;
  a17=(a17-a07);
  a17=(a17/a04);
  a17=(a18-a17);
  a17=(a17/a04);
  a17=(a00*a17);
  a05=(a05-a24);
  a24=casadi_sq(a05);
  a09=(a09-a31);
  a31=casadi_sq(a09);
  a24=(a24+a31);
  a24=(a24+a11);
  a24=sqrt(a24);
  a05=(a05/a24);
  a14=(a24-a14);
  a14=(a14/a16);
  a14=(-a14);
  a14=exp(a14);
  a14=(a13+a14);
  a14=log(a14);
  a14=(a12*a14);
  a16=(a18-a34);
  a11=(a05*a16);
  a09=(a09/a24);
  a24=(a23-a37);
  a31=(a09*a24);
  a11=(a11+a31);
  a11=(a11/a25);
  a26=(a11<a26);
  a13=(a13-a11);
  a13=(a26?a13:0);
  a26=(!a26);
  a25=(a11<a12);
  a11=(a11-a12);
  a11=casadi_sq(a11);
  a11=(a11/a30);
  a25=(a25?a11:0);
  a26=(a26?a25:0);
  a13=(a13+a26);
  a26=(a14*a13);
  a25=(a05*a26);
  a24=(a05*a24);
  a16=(a09*a16);
  a24=(a24-a16);
  a20=(a20*a24);
  a20=(a20*a14);
  a20=(a20*a13);
  a24=casadi_sq(a24);
  a24=(a28+a24);
  a24=sqrt(a24);
  a20=(a20/a24);
  a24=(a09*a20);
  a25=(a25-a24);
  a29=(a25-a29);
  a24=(a40*a18);
  a18=casadi_sq(a18);
  a13=casadi_sq(a23);
  a18=(a18+a13);
  a18=(a28+a18);
  a18=sqrt(a18);
  a24=(a24/a18);
  a29=(a29+a24);
  a17=(a17-a29);
  if (res[0]!=0) res[0][2]=a17;
  a17=arg[0]? arg[0][3] : 0;
  a22=(a22-a17);
  a22=(a22/a04);
  a22=(a23-a22);
  a22=(a22/a04);
  a22=(a00*a22);
  a05=(a05*a20);
  a09=(a09*a26);
  a05=(a05+a09);
  a06=(a05-a06);
  a23=(a40*a23);
  a23=(a23/a18);
  a06=(a06+a23);
  a22=(a22-a06);
  if (res[0]!=0) res[0][3]=a22;
  a22=arg[0]? arg[0][4] : 0;
  a33=(a33-a22);
  a33=(a33/a04);
  a33=(a34-a33);
  a33=(a33/a04);
  a33=(a00*a33);
  a22=(a40*a34);
  a34=casadi_sq(a34);
  a06=casadi_sq(a37);
  a34=(a34+a06);
  a28=(a28+a34);
  a28=sqrt(a28);
  a22=(a22/a28);
  a25=(a25+a41);
  a22=(a22-a25);
  a33=(a33-a22);
  if (res[0]!=0) res[0][4]=a33;
  a33=arg[0]? arg[0][5] : 0;
  a15=(a15-a33);
  a15=(a15/a04);
  a15=(a37-a15);
  a15=(a15/a04);
  a00=(a00*a15);
  a40=(a40*a37);
  a40=(a40/a28);
  a05=(a05+a01);
  a40=(a40-a05);
  a00=(a00-a40);
  if (res[0]!=0) res[0][5]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int func0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int func0_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int func0_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void func0_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int func0_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void func0_release(int mem) {
}

CASADI_SYMBOL_EXPORT void func0_incref(void) {
}

CASADI_SYMBOL_EXPORT void func0_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int func0_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int func0_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real func0_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* func0_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* func0_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* func0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* func0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int func0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int func0_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_func0(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  int mem;
  casadi_real w[66];
  casadi_int *iw = 0;
  const casadi_real* arg[3] = {0};
  casadi_real* res[1] = {0};
  if (argc>3) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"func0\" failed. Too many input arguments (%d, max 3)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"func0\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s1, w+24);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+6, casadi_s1, w+24);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+12, casadi_s1, w+24);
  --resc;
  res[0] = w+18;
  func0_incref();
  mem = func0_checkout();
  i = func0(arg, res, iw, w+24, mem);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"func0\" failed.");
  func0_release(mem);
  func0_decref();
  if (res[0]) resv[0] = casadi_to_mex(casadi_s1, res[0]);
}
#endif

casadi_int main_func0(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int *iw = 0;
  casadi_real w[66];
  const casadi_real* arg[3];
  casadi_real* res[1];
  arg[0] = w+0;
  arg[1] = w+6;
  arg[2] = w+12;
  res[0] = w+18;
  a = w;
  for (j=0; j<18; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = func0(arg, res, iw, w+24, 0);
  if (flag) return flag;
  r = w+18;
  for (j=0; j<6; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[6];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_func0(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "func0")==0) {
    mex_func0(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'func0'");
}
#endif
CASADI_SYMBOL_EXPORT int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "func0")==0) {
    return main_func0(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'func0'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
