/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) getUdqn_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {6, 6, 1};
static const casadi_int casadi_s2[10] = 
  {6, 1, 0, 6, 0, 1, 2, 3,
  4, 5};
static const casadi_int casadi_s3[45] = 
  {6, 6, 0, 6, 12, 18, 24, 30,
  36, 0, 1, 2, 3, 4, 5, 0,
  1, 2, 3, 4, 5, 0, 1, 2,
  3, 4, 5, 0, 1, 2, 3, 4,
  5, 0, 1, 2, 3, 4, 5, 0,
  1, 2, 3, 4, 5};

/* func2:(i0[6],i1[6],i2[6])->(o0[6x6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62;
  a00=-4000.;
  a01=arg[2]? arg[2][0] : 0;
  a02=arg[2]? arg[2][2] : 0;
  a03=(a01-a02);
  a04=casadi_sq(a03);
  a05=arg[2]? arg[2][1] : 0;
  a06=arg[2]? arg[2][3] : 0;
  a07=(a05-a06);
  a08=casadi_sq(a07);
  a04=(a04+a08);
  a08=9.9999999999999998e-13;
  a04=(a04+a08);
  a04=sqrt(a04);
  a03=(a03/a04);
  a09=2.;
  a10=1.;
  a11=1.6000000000000000e-01;
  a12=(a04-a11);
  a13=1.0000000000000000e-03;
  a12=(a12/a13);
  a12=(-a12);
  a12=exp(a12);
  a12=(a10+a12);
  a12=log(a12);
  a12=(a09*a12);
  a14=arg[1]? arg[1][0] : 0;
  a14=(a01-a14);
  a15=1.0000000000000000e-02;
  a14=(a14/a15);
  a16=arg[1]? arg[1][2] : 0;
  a16=(a02-a16);
  a16=(a16/a15);
  a17=(a14-a16);
  a18=(a03*a17);
  a07=(a07/a04);
  a04=arg[1]? arg[1][1] : 0;
  a04=(a05-a04);
  a04=(a04/a15);
  a19=arg[1]? arg[1][3] : 0;
  a19=(a06-a19);
  a19=(a19/a15);
  a20=(a04-a19);
  a21=(a07*a20);
  a18=(a18+a21);
  a21=5.0000000000000000e-01;
  a18=(a18/a21);
  a22=0.;
  a23=(a18<a22);
  a24=-100.;
  a25=(a24*a03);
  a25=(a09*a25);
  a26=(-a25);
  a26=(a23?a26:0);
  a27=(!a23);
  a28=(a18<a09);
  a29=2.5000000000000000e-01;
  a30=(a18-a09);
  a31=(a30+a30);
  a25=(a31*a25);
  a25=(a29*a25);
  a25=(a28?a25:0);
  a25=(a27?a25:0);
  a26=(a26+a25);
  a25=(a12*a26);
  a32=(a03*a25);
  a33=-5.0000000000000000e-01;
  a20=(a03*a20);
  a17=(a07*a17);
  a20=(a20-a17);
  a17=(a33*a20);
  a17=(a17*a12);
  a26=(a17*a26);
  a18=(a10-a18);
  a18=(a23?a18:0);
  a30=casadi_sq(a30);
  a34=4.;
  a30=(a30/a34);
  a30=(a28?a30:0);
  a30=(a27?a30:0);
  a18=(a18+a30);
  a30=(a24*a07);
  a35=(a33*a30);
  a35=(a12*a35);
  a35=(a18*a35);
  a26=(a26-a35);
  a35=2.5000000000000005e-03;
  a36=casadi_sq(a20);
  a36=(a35+a36);
  a36=sqrt(a36);
  a26=(a26/a36);
  a37=(a17*a18);
  a37=(a37/a36);
  a37=(a37/a36);
  a20=(a20+a20);
  a30=(a20*a30);
  a38=(a36+a36);
  a30=(a30/a38);
  a30=(a37*a30);
  a26=(a26+a30);
  a30=(a07*a26);
  a32=(a32-a30);
  a30=arg[2]? arg[2][4] : 0;
  a01=(a01-a30);
  a39=casadi_sq(a01);
  a40=arg[2]? arg[2][5] : 0;
  a05=(a05-a40);
  a41=casadi_sq(a05);
  a39=(a39+a41);
  a39=(a39+a08);
  a39=sqrt(a39);
  a01=(a01/a39);
  a41=(a39-a11);
  a41=(a41/a13);
  a41=(-a41);
  a41=exp(a41);
  a41=(a10+a41);
  a41=log(a41);
  a41=(a09*a41);
  a42=arg[1]? arg[1][4] : 0;
  a42=(a30-a42);
  a42=(a42/a15);
  a43=(a14-a42);
  a44=(a01*a43);
  a05=(a05/a39);
  a39=arg[1]? arg[1][5] : 0;
  a39=(a40-a39);
  a39=(a39/a15);
  a15=(a04-a39);
  a45=(a05*a15);
  a44=(a44+a45);
  a44=(a44/a21);
  a45=(a44<a22);
  a46=(a24*a01);
  a46=(a09*a46);
  a47=(-a46);
  a47=(a45?a47:0);
  a48=(!a45);
  a49=(a44<a09);
  a50=(a44-a09);
  a51=(a50+a50);
  a46=(a51*a46);
  a46=(a29*a46);
  a46=(a49?a46:0);
  a46=(a48?a46:0);
  a47=(a47+a46);
  a46=(a41*a47);
  a52=(a01*a46);
  a15=(a01*a15);
  a43=(a05*a43);
  a15=(a15-a43);
  a43=(a33*a15);
  a43=(a43*a41);
  a47=(a43*a47);
  a44=(a10-a44);
  a44=(a45?a44:0);
  a50=casadi_sq(a50);
  a50=(a50/a34);
  a50=(a49?a50:0);
  a50=(a48?a50:0);
  a44=(a44+a50);
  a50=(a24*a05);
  a53=(a33*a50);
  a53=(a41*a53);
  a53=(a44*a53);
  a47=(a47-a53);
  a53=casadi_sq(a15);
  a53=(a35+a53);
  a53=sqrt(a53);
  a47=(a47/a53);
  a54=(a43*a44);
  a54=(a54/a53);
  a54=(a54/a53);
  a15=(a15+a15);
  a50=(a15*a50);
  a55=(a53+a53);
  a50=(a50/a55);
  a50=(a54*a50);
  a47=(a47+a50);
  a50=(a05*a47);
  a52=(a52-a50);
  a50=(a32+a52);
  a56=9.8100000000000023e+00;
  a57=casadi_sq(a14);
  a58=casadi_sq(a04);
  a57=(a57+a58);
  a57=(a35+a57);
  a57=sqrt(a57);
  a58=(a56/a57);
  a59=-9.8100000000000021e-02;
  a60=(a59*a14);
  a60=(a60/a57);
  a60=(a60/a57);
  a14=(a14+a14);
  a14=(a24*a14);
  a61=(a57+a57);
  a14=(a14/a61);
  a62=(a60*a14);
  a58=(a58-a62);
  a50=(a50+a58);
  a50=(a00-a50);
  if (res[0]!=0) res[0][0]=a50;
  a26=(a03*a26);
  a25=(a07*a25);
  a26=(a26+a25);
  a47=(a01*a47);
  a46=(a05*a46);
  a47=(a47+a46);
  a46=(a26+a47);
  a25=(a59*a04);
  a25=(a25/a57);
  a25=(a25/a57);
  a14=(a25*a14);
  a46=(a46-a14);
  a46=(-a46);
  if (res[0]!=0) res[0][1]=a46;
  if (res[0]!=0) res[0][2]=a32;
  if (res[0]!=0) res[0][3]=a26;
  if (res[0]!=0) res[0][4]=a52;
  if (res[0]!=0) res[0][5]=a47;
  a47=(a24*a07);
  a47=(a09*a47);
  a52=(-a47);
  a52=(a23?a52:0);
  a47=(a31*a47);
  a47=(a29*a47);
  a47=(a28?a47:0);
  a47=(a27?a47:0);
  a52=(a52+a47);
  a47=(a12*a52);
  a26=(a03*a47);
  a32=(a24*a03);
  a46=(a33*a32);
  a46=(a12*a46);
  a46=(a18*a46);
  a52=(a17*a52);
  a46=(a46+a52);
  a46=(a46/a36);
  a32=(a20*a32);
  a32=(a32/a38);
  a32=(a37*a32);
  a46=(a46-a32);
  a32=(a07*a46);
  a26=(a26-a32);
  a32=(a24*a05);
  a32=(a09*a32);
  a52=(-a32);
  a52=(a45?a52:0);
  a32=(a51*a32);
  a32=(a29*a32);
  a32=(a49?a32:0);
  a32=(a48?a32:0);
  a52=(a52+a32);
  a32=(a41*a52);
  a14=(a01*a32);
  a50=(a24*a01);
  a58=(a33*a50);
  a58=(a41*a58);
  a58=(a44*a58);
  a52=(a43*a52);
  a58=(a58+a52);
  a58=(a58/a53);
  a50=(a15*a50);
  a50=(a50/a55);
  a50=(a54*a50);
  a58=(a58-a50);
  a50=(a05*a58);
  a14=(a14-a50);
  a50=(a26+a14);
  a04=(a04+a04);
  a04=(a24*a04);
  a04=(a04/a61);
  a60=(a60*a04);
  a50=(a50-a60);
  a50=(-a50);
  if (res[0]!=0) res[0][6]=a50;
  a46=(a03*a46);
  a47=(a07*a47);
  a46=(a46+a47);
  a58=(a01*a58);
  a32=(a05*a32);
  a58=(a58+a32);
  a32=(a46+a58);
  a57=(a56/a57);
  a25=(a25*a04);
  a57=(a57-a25);
  a32=(a32+a57);
  a32=(a00-a32);
  if (res[0]!=0) res[0][7]=a32;
  if (res[0]!=0) res[0][8]=a26;
  if (res[0]!=0) res[0][9]=a46;
  if (res[0]!=0) res[0][10]=a14;
  if (res[0]!=0) res[0][11]=a58;
  a58=100.;
  a14=(a58*a03);
  a14=(a09*a14);
  a46=(-a14);
  a46=(a23?a46:0);
  a14=(a31*a14);
  a14=(a29*a14);
  a14=(a28?a14:0);
  a14=(a27?a14:0);
  a46=(a46+a14);
  a14=(a12*a46);
  a26=(a03*a14);
  a46=(a17*a46);
  a32=(a58*a07);
  a57=(a33*a32);
  a57=(a12*a57);
  a57=(a18*a57);
  a46=(a46-a57);
  a46=(a46/a36);
  a32=(a20*a32);
  a32=(a32/a38);
  a32=(a37*a32);
  a46=(a46+a32);
  a32=(a07*a46);
  a26=(a26-a32);
  a32=(-a26);
  if (res[0]!=0) res[0][12]=a32;
  a46=(a03*a46);
  a14=(a07*a14);
  a46=(a46+a14);
  a14=(-a46);
  if (res[0]!=0) res[0][13]=a14;
  a02=(a02-a30);
  a30=casadi_sq(a02);
  a06=(a06-a40);
  a40=casadi_sq(a06);
  a30=(a30+a40);
  a30=(a30+a08);
  a30=sqrt(a30);
  a02=(a02/a30);
  a11=(a30-a11);
  a11=(a11/a13);
  a11=(-a11);
  a11=exp(a11);
  a11=(a10+a11);
  a11=log(a11);
  a11=(a09*a11);
  a13=(a16-a42);
  a08=(a02*a13);
  a06=(a06/a30);
  a30=(a19-a39);
  a40=(a06*a30);
  a08=(a08+a40);
  a08=(a08/a21);
  a22=(a08<a22);
  a21=(a24*a02);
  a21=(a09*a21);
  a40=(-a21);
  a40=(a22?a40:0);
  a14=(!a22);
  a32=(a08<a09);
  a57=(a08-a09);
  a25=(a57+a57);
  a21=(a25*a21);
  a21=(a29*a21);
  a21=(a32?a21:0);
  a21=(a14?a21:0);
  a40=(a40+a21);
  a21=(a11*a40);
  a04=(a02*a21);
  a30=(a02*a30);
  a13=(a06*a13);
  a30=(a30-a13);
  a13=(a33*a30);
  a13=(a13*a11);
  a40=(a13*a40);
  a10=(a10-a08);
  a10=(a22?a10:0);
  a57=casadi_sq(a57);
  a57=(a57/a34);
  a57=(a32?a57:0);
  a57=(a14?a57:0);
  a10=(a10+a57);
  a57=(a24*a06);
  a34=(a33*a57);
  a34=(a11*a34);
  a34=(a10*a34);
  a40=(a40-a34);
  a34=casadi_sq(a30);
  a34=(a35+a34);
  a34=sqrt(a34);
  a40=(a40/a34);
  a08=(a13*a10);
  a08=(a08/a34);
  a08=(a08/a34);
  a30=(a30+a30);
  a57=(a30*a57);
  a47=(a34+a34);
  a57=(a57/a47);
  a57=(a08*a57);
  a40=(a40+a57);
  a57=(a06*a40);
  a04=(a04-a57);
  a26=(a04-a26);
  a57=casadi_sq(a16);
  a50=casadi_sq(a19);
  a57=(a57+a50);
  a57=(a35+a57);
  a57=sqrt(a57);
  a50=(a56/a57);
  a60=(a59*a16);
  a60=(a60/a57);
  a60=(a60/a57);
  a16=(a16+a16);
  a16=(a24*a16);
  a61=(a57+a57);
  a16=(a16/a61);
  a52=(a60*a16);
  a50=(a50-a52);
  a26=(a26+a50);
  a26=(a00-a26);
  if (res[0]!=0) res[0][14]=a26;
  a40=(a02*a40);
  a21=(a06*a21);
  a40=(a40+a21);
  a46=(a40-a46);
  a21=(a59*a19);
  a21=(a21/a57);
  a21=(a21/a57);
  a16=(a21*a16);
  a46=(a46-a16);
  a46=(-a46);
  if (res[0]!=0) res[0][15]=a46;
  if (res[0]!=0) res[0][16]=a04;
  if (res[0]!=0) res[0][17]=a40;
  a40=(a58*a07);
  a40=(a09*a40);
  a04=(-a40);
  a23=(a23?a04:0);
  a31=(a31*a40);
  a31=(a29*a31);
  a28=(a28?a31:0);
  a27=(a27?a28:0);
  a23=(a23+a27);
  a27=(a12*a23);
  a28=(a03*a27);
  a31=(a58*a03);
  a40=(a33*a31);
  a12=(a12*a40);
  a18=(a18*a12);
  a17=(a17*a23);
  a18=(a18+a17);
  a18=(a18/a36);
  a20=(a20*a31);
  a20=(a20/a38);
  a37=(a37*a20);
  a18=(a18-a37);
  a37=(a07*a18);
  a28=(a28-a37);
  a37=(-a28);
  if (res[0]!=0) res[0][18]=a37;
  a03=(a03*a18);
  a07=(a07*a27);
  a03=(a03+a07);
  a07=(-a03);
  if (res[0]!=0) res[0][19]=a07;
  a07=(a24*a06);
  a07=(a09*a07);
  a27=(-a07);
  a27=(a22?a27:0);
  a07=(a25*a07);
  a07=(a29*a07);
  a07=(a32?a07:0);
  a07=(a14?a07:0);
  a27=(a27+a07);
  a07=(a11*a27);
  a18=(a02*a07);
  a37=(a24*a02);
  a20=(a33*a37);
  a20=(a11*a20);
  a20=(a10*a20);
  a27=(a13*a27);
  a20=(a20+a27);
  a20=(a20/a34);
  a37=(a30*a37);
  a37=(a37/a47);
  a37=(a08*a37);
  a20=(a20-a37);
  a37=(a06*a20);
  a18=(a18-a37);
  a28=(a18-a28);
  a19=(a19+a19);
  a19=(a24*a19);
  a19=(a19/a61);
  a60=(a60*a19);
  a28=(a28-a60);
  a28=(-a28);
  if (res[0]!=0) res[0][20]=a28;
  a20=(a02*a20);
  a07=(a06*a07);
  a20=(a20+a07);
  a03=(a20-a03);
  a57=(a56/a57);
  a21=(a21*a19);
  a57=(a57-a21);
  a03=(a03+a57);
  a03=(a00-a03);
  if (res[0]!=0) res[0][21]=a03;
  if (res[0]!=0) res[0][22]=a18;
  if (res[0]!=0) res[0][23]=a20;
  a20=(a58*a01);
  a20=(a09*a20);
  a18=(-a20);
  a18=(a45?a18:0);
  a20=(a51*a20);
  a20=(a29*a20);
  a20=(a49?a20:0);
  a20=(a48?a20:0);
  a18=(a18+a20);
  a20=(a41*a18);
  a03=(a01*a20);
  a18=(a43*a18);
  a57=(a58*a05);
  a21=(a33*a57);
  a21=(a41*a21);
  a21=(a44*a21);
  a18=(a18-a21);
  a18=(a18/a53);
  a57=(a15*a57);
  a57=(a57/a55);
  a57=(a54*a57);
  a18=(a18+a57);
  a57=(a05*a18);
  a03=(a03-a57);
  a57=(-a03);
  if (res[0]!=0) res[0][24]=a57;
  a18=(a01*a18);
  a20=(a05*a20);
  a18=(a18+a20);
  a20=(-a18);
  if (res[0]!=0) res[0][25]=a20;
  a20=(a58*a02);
  a20=(a09*a20);
  a57=(-a20);
  a57=(a22?a57:0);
  a20=(a25*a20);
  a20=(a29*a20);
  a20=(a32?a20:0);
  a20=(a14?a20:0);
  a57=(a57+a20);
  a20=(a11*a57);
  a21=(a02*a20);
  a57=(a13*a57);
  a19=(a58*a06);
  a07=(a33*a19);
  a07=(a11*a07);
  a07=(a10*a07);
  a57=(a57-a07);
  a57=(a57/a34);
  a19=(a30*a19);
  a19=(a19/a47);
  a19=(a08*a19);
  a57=(a57+a19);
  a19=(a06*a57);
  a21=(a21-a19);
  a19=(-a21);
  if (res[0]!=0) res[0][26]=a19;
  a57=(a02*a57);
  a20=(a06*a20);
  a57=(a57+a20);
  a20=(-a57);
  if (res[0]!=0) res[0][27]=a20;
  a20=casadi_sq(a42);
  a19=casadi_sq(a39);
  a20=(a20+a19);
  a35=(a35+a20);
  a35=sqrt(a35);
  a20=(a56/a35);
  a19=(a59*a42);
  a19=(a19/a35);
  a19=(a19/a35);
  a42=(a42+a42);
  a42=(a24*a42);
  a07=(a35+a35);
  a42=(a42/a07);
  a28=(a19*a42);
  a20=(a20-a28);
  a21=(a21+a03);
  a20=(a20-a21);
  a20=(a00-a20);
  if (res[0]!=0) res[0][28]=a20;
  a59=(a59*a39);
  a59=(a59/a35);
  a59=(a59/a35);
  a42=(a59*a42);
  a57=(a57+a18);
  a42=(a42+a57);
  if (res[0]!=0) res[0][29]=a42;
  a42=(a58*a05);
  a42=(a09*a42);
  a57=(-a42);
  a45=(a45?a57:0);
  a51=(a51*a42);
  a51=(a29*a51);
  a49=(a49?a51:0);
  a48=(a48?a49:0);
  a45=(a45+a48);
  a48=(a41*a45);
  a49=(a01*a48);
  a51=(a58*a01);
  a42=(a33*a51);
  a41=(a41*a42);
  a44=(a44*a41);
  a43=(a43*a45);
  a44=(a44+a43);
  a44=(a44/a53);
  a15=(a15*a51);
  a15=(a15/a55);
  a54=(a54*a15);
  a44=(a44-a54);
  a54=(a05*a44);
  a49=(a49-a54);
  a54=(-a49);
  if (res[0]!=0) res[0][30]=a54;
  a01=(a01*a44);
  a05=(a05*a48);
  a01=(a01+a05);
  a05=(-a01);
  if (res[0]!=0) res[0][31]=a05;
  a05=(a58*a06);
  a09=(a09*a05);
  a05=(-a09);
  a22=(a22?a05:0);
  a25=(a25*a09);
  a29=(a29*a25);
  a32=(a32?a29:0);
  a14=(a14?a32:0);
  a22=(a22+a14);
  a14=(a11*a22);
  a32=(a02*a14);
  a58=(a58*a02);
  a33=(a33*a58);
  a11=(a11*a33);
  a10=(a10*a11);
  a13=(a13*a22);
  a10=(a10+a13);
  a10=(a10/a34);
  a30=(a30*a58);
  a30=(a30/a47);
  a08=(a08*a30);
  a10=(a10-a08);
  a08=(a06*a10);
  a32=(a32-a08);
  a08=(-a32);
  if (res[0]!=0) res[0][32]=a08;
  a02=(a02*a10);
  a06=(a06*a14);
  a02=(a02+a06);
  a06=(-a02);
  if (res[0]!=0) res[0][33]=a06;
  a39=(a39+a39);
  a24=(a24*a39);
  a24=(a24/a07);
  a19=(a19*a24);
  a32=(a32+a49);
  a19=(a19+a32);
  if (res[0]!=0) res[0][34]=a19;
  a56=(a56/a35);
  a59=(a59*a24);
  a56=(a56-a59);
  a02=(a02+a01);
  a56=(a56-a02);
  a00=(a00-a56);
  if (res[0]!=0) res[0][35]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int func2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int func2_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int func2_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void func2_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int func2_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void func2_release(int mem) {
}

CASADI_SYMBOL_EXPORT void func2_incref(void) {
}

CASADI_SYMBOL_EXPORT void func2_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int func2_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int func2_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real func2_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* func2_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* func2_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* func2_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* func2_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int func2_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int func2_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_func2(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  int mem;
  casadi_real w[117];
  casadi_int *iw = 0;
  const casadi_real* arg[3] = {0};
  casadi_real* res[1] = {0};
  if (argc>3) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"func2\" failed. Too many input arguments (%d, max 3)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"func2\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s2, w+54);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+6, casadi_s2, w+54);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+12, casadi_s2, w+54);
  --resc;
  res[0] = w+18;
  func2_incref();
  mem = func2_checkout();
  i = func2(arg, res, iw, w+54, mem);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"func2\" failed.");
  func2_release(mem);
  func2_decref();
  if (res[0]) resv[0] = casadi_to_mex(casadi_s3, res[0]);
}
#endif

casadi_int main_func2(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int *iw = 0;
  casadi_real w[117];
  const casadi_real* arg[3];
  casadi_real* res[1];
  arg[0] = w+0;
  arg[1] = w+6;
  arg[2] = w+12;
  res[0] = w+18;
  a = w;
  for (j=0; j<18; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = func2(arg, res, iw, w+54, 0);
  if (flag) return flag;
  r = w+18;
  for (j=0; j<36; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[6];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_func2(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "func2")==0) {
    mex_func2(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'func2'");
}
#endif
CASADI_SYMBOL_EXPORT int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "func2")==0) {
    return main_func2(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'func2'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
